Item Translation Fixes & Updates
llchrisll/ROenglishRE pull request #18
Opened 2021-06-10 17:06 UTC by Everade

* Fixes various wrong item descriptions
* Added some missing translations
* Some misc. cleanup

Based on official KRO descriptions and has been confirmed on rAthena & Divine-Pride

2021-06-10 17:53 UTC, llchrisll requested changes
From the looks it's fine so far except the mentioned lines.
Once you have fixed those and merged the commit I'm about to do, I will approve it :).
Thanks for the contribution.
Normally I request the other itemInfo's as well, as I update all of them at once with the same stuff.
But since it's this itemInfo, I will update the others as well.

2021-06-10 17:53 UTC, llchrisll commented on Client Support/Renewal/2020-09-02/System/itemInfo_EN.lua
> -			"^663399Indestructible in battle^000000",
Not sure why you delete it:
`제련불가. 파괴불가.` = `Impossible to smelt. indestructible.`

2021-06-10 17:53 UTC, llchrisll commented on Client Support/Renewal/2020-09-02/System/itemInfo_EN.lua
> -			"^0000CCArmor Level:^000000 1",			"________________________",			"^0000CCRequirement:^000000",
Just funny how my local file is fine regarding that, but the uploaded one not xD.

2021-06-10 17:53 UTC, llchrisll commented on Client Support/Renewal/2020-09-02/System/itemInfo_EN.lua
> +			"MDEF +1 per 2 refine Lv.",
Replace it with ```
"^0000FFFor each 2 Refine Levels^000000:",
"MDEF+1",```

2021-06-10 17:53 UTC, llchrisll commented on Client Support/Renewal/2020-09-02/System/itemInfo_EN.lua
>  			"Every Refine Increases MATK.",
If you fix something, please check other lines as well and replace this as well with:
```
"^0000FFFor each Refine Level^000000:",
"MATK + 1",
```

2021-06-10 20:42 UTC, llchrisll requested changes
Like mentioned, here the new commit, as I updated the default project version to 2018-06-20, the folder layout also changed a bit:
0ecc52e0853ffb37c0d0d2f4edbc89c4c838bc16
Once you have updated the `Renewal/System/itemInfo_EN.lua` with your file, I will be able to merge it ^^. It might be more difficult for now, but a bit of work for ya :P.

2021-06-10 21:45 UTC, Everade commented
Aint got no time for that.

2021-06-10 21:45 UTC, closed without merging

2021-06-11 05:42 UTC, llchrisll commented
K I will do it myself then^^.
I do it since 2019, so I'm used to long term work haha.
Also not sure what you did to fix the issue with \r since I can't view that commit correctly. I guess use \n instead but well.

2021-06-11 10:15 UTC, Everade commented
i searched and replaced all \r(tab)  with \n\r(tab)
you can use notepad++ to do that.