Remove duplicate entries in cardpostfixnametable.txt
llchrisll/ROenglishRE pull request #28
Opened 2022-03-15 16:58 UTC by Daraen1

Remove duplicate entries in cardpostfixnametable.txt

issue #27 

I was bored so I decided to do it. Tell me if something wrong.
Thanks to @Everade for reporting this issue.

2022-03-15 17:51 UTC, llchrisll commented
Well I did it already locally, also you forgot to update the https://github.com/llchrisll/ROenglishRE/blob/master/Addons/jRO%20Enchants%20Display/data/cardpostfixnametable.txt
as well :P

2022-03-15 18:42 UTC, Daraen1 commented
No worries, I'll do it a bit later in the evening

2022-03-16 00:16 UTC, Everade requested changes

2022-03-16 00:16 UTC, Everade commented on Renewal/data/cardpostfixnametable.txt
> +300130#
You missed these
```
300128#
300130#
```

2022-03-16 22:41 UTC, Daraen1 commented on Renewal/data/cardpostfixnametable.txt
> +300130#
Sorry and Thanks :)

2022-03-17 01:32 UTC, Daraen1 commented on Renewal/data/cardpostfixnametable.txt
> +300130#
update :)

2022-03-21 06:44 UTC, merged